### ISSUE TITLE
iStats MEM Temp + Usage Not fully working

### ISSUE THREAD

**Issue by hungip** [marekkaczkowski/Touch-Bar-iStats#4]
This Json file is working but not fully

my touch bar only displays temperature, no more

and i found on my mac os dont have commnd "numfmt"

**Comment by marekkaczkowski** [comment]
Hey @hungip 

> my touch bar only displays temperature, no more

Yeap, it just pipes `istats` temp value to btt - nothing more, nothing less 🙂

> and i found on my mac os dont have commnd "numfmt"

`numfmt` is a part of GNU Coreutils (you can [install it via brew](https://formulae.brew.sh/formula/coreutils)).
